name: update-submodule

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  update-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        repository: ${{ github.repository_owner }}/LivestreamRecorderService
        ref: master
    - uses: fatjyc/update-submodule-action@v9.0
      with:
        repo: LivestreamRecorderService
        user: ${{ github.repository_owner }}
        token: ${{ secrets.CR_PAT }}
        repo_owner: ${{ github.repository_owner }}
        committor_username: ${{ github.repository_owner }}
        committor_email: actions@github.com
        path: ${{ github.event.repository.name }}
  update-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        repository: ${{ github.repository_owner }}/LivestreamRecorderBackend
        ref: dev
    - uses: fatjyc/update-submodule-action@v9.0
      with:
        repo: LivestreamRecorderBackend
        user: ${{ github.repository_owner }}
        token: ${{ secrets.CR_PAT }}
        repo_owner: ${{ github.repository_owner }}
        committor_username: ${{ github.repository_owner }}
        committor_email: actions@github.com
        path: ${{ github.event.repository.name }}
